-- OctoTravel data: zone dimensions + travel nodes.
-- Zone sizes (yards, {width, height}) taken from pfQuest's pfDB["minimap"]
-- (MIT) and pfQuest-octo's minimap-turtle.lua for Turtle custom zones.
-- Keys are enUS world-map zone names as returned by GetMapZones().

OctoTravel_Zones = {
  -- Eastern Kingdoms
  ["Dun Morogh"]           = { 4925.0, 3283.34 },
  ["Badlands"]             = { 2487.5, 1658.34 },
  ["Blasted Lands"]        = { 3350.0, 2233.3 },
  ["Swamp of Sorrows"]     = { 2293.75, 1529.17 },
  ["Duskwood"]             = { 2700.003, 1800.03 },
  ["Wetlands"]             = { 4135.417, 2756.25 },
  ["Elwynn Forest"]        = { 3470.84, 2314.62 },
  ["The Barrens"]          = { 10133.34, 6756.25 },
  ["Western Plaguelands"]  = { 4299.997, 2866.67 },
  ["Stranglethorn Vale"]   = { 6381.25, 4254.1 },
  ["Alterac Mountains"]    = { 2800.003, 1866.667 },
  ["Loch Modan"]           = { 2758.33, 1839.58 },
  ["Westfall"]             = { 3500.003, 2333.3 },
  ["Deadwind Pass"]        = { 2499.997, 1666.63 },
  ["Redridge Mountains"]   = { 2170.84, 1447.9 },
  ["Arathi Highlands"]     = { 3600.003, 2399.997 },
  ["Burning Steppes"]      = { 2929.163, 1952.08 },
  ["The Hinterlands"]      = { 3850.0, 2566.67 },
  ["Searing Gorge"]        = { 2231.253, 1487.5 },
  ["Tirisfal Glades"]      = { 4518.75, 3012.5 },
  ["Silverpine Forest"]    = { 4200.0, 2800.0 },
  ["Eastern Plaguelands"]  = { 3870.83, 2581.25 },
  ["Hillsbrad Foothills"]  = { 3200.0, 2133.33 },
  -- Kalimdor
  ["Durotar"]              = { 5287.5, 3525.0 },
  ["Dustwallow Marsh"]     = { 5250.0, 3500.0 },
  ["Azshara"]              = { 5070.84, 3381.25 },
  ["Teldrassil"]           = { 5091.66, 3393.7 },
  ["Darkshore"]            = { 6550.0, 4366.66 },
  ["Mulgore"]              = { 5137.5, 3425.003 },
  ["Ashenvale"]            = { 5766.67, 3843.753 },
  ["Feralas"]              = { 6950.0, 4633.33 },
  ["Felwood"]              = { 5750.0, 3833.33 },
  ["Thousand Needles"]     = { 4399.997, 2933.33 },
  ["Desolace"]             = { 4495.83, 2997.913 },
  ["Stonetalon Mountains"] = { 4883.33, 3256.253 },
  ["Tanaris"]              = { 6900.0, 4600.0 },
  ["Moonglade"]            = { 2308.33, 1539.59 },
  ["Winterspring"]         = { 7100.003, 4733.33 },
  ["Silithus"]             = { 3483.334, 2322.92 },
  ["Un'Goro Crater"]       = { 3700.003, 2466.66 },
  -- Cities
  ["Undercity"]            = { 959.3754, 640.11 },
  ["Stormwind City"]       = { 1344.2694, 896.36 },
  ["Ironforge"]            = { 790.629, 527.61 },
  ["Orgrimmar"]            = { 1402.61, 935.42 },
  ["Thunder Bluff"]        = { 1043.75, 695.83 },
  ["Darnassus"]            = { 1058.33, 705.71 },
  -- Turtle/Octo custom zones (pfQuest-octo minimap-turtle.lua)
  ["Lapidis Isle"]         = { 2901.45, 1915.9 },
  ["Alah'Thalas"]          = { 1468.0, 976.0 },
  ["Scarlet Enclave"]      = { 3159.0, 2108.0 },
  ["Icepoint Rock"]        = { 1608.0, 1075.0 },
  ["Tel'Abim"]             = { 3227.0, 2187.0 },
  ["Gilneas"]              = { 3666.0, 2442.0 },
  ["Thalassian Highlands"] = { 3082.0, 2061.0 },
  ["Blackstone Island"]    = { 2472.0, 1665.0 },
  ["Balor"]                = { 3098.0, 2068.0 },
  ["Northwind"]            = { 3241.0, 2157.0 },
  ["Grim Reaches"]         = { 5387.0, 3584.0 },
  ["Hyjal"]                = { 3206.0, 2142.0 },
  ["Gillijim's Isle"]      = { 3092.1, 2047.0 },
  ["Moonwhisper Coast"]    = { 5241.0, 7856.0 },
}

-- Travel nodes. Fields:
--   map  = enUS zone name (must be a key above for minimap support)
--   x, y = map coordinates in percent
--   t    = boat | zeppelin | tram | flight | rental | portal
--   name = tooltip title
--   dest = destination text; destmap = zone name to open on click
--   time / freq / price / note = extra tooltip lines
--   faction = "A" | "H" (omit for neutral)
--   icon = per-node icon override
OctoTravel_Nodes = {
  -- ============================================================= boats ==
  -- Coords from the 1.12 db dock triggers; times are community-measured
  -- approximations (vanilla schedules drift with server restarts).
  { map = "Wetlands", x = 5.8, y = 63.4, t = "boat", name = "Menethil Harbor - South Pier",
    dest = "Theramore Isle (Dustwallow Marsh)", destmap = "Dustwallow Marsh",
    time = "Crossing: ~3-5 min", freq = "Departs: ~every 7-10 min" },
  { map = "Wetlands", x = 5.2, y = 57.7, t = "boat", name = "Menethil Harbor - North Pier",
    dest = "Auberdine (Darkshore)", destmap = "Darkshore",
    time = "Crossing: ~4-5 min", freq = "Departs: ~every 7-10 min" },
  { map = "Darkshore", x = 32.3, y = 43.8, t = "boat", name = "Auberdine Pier",
    routes = {
      { dest = "Rut'theran Village (Teldrassil) - north berth", time = "Crossing: ~1-2 min, ~every 4-5 min" },
      { dest = "Menethil Harbor (Wetlands) - southwest berth", time = "Crossing: ~4-5 min, ~every 7-10 min" },
      { dest = "Stormwind Harbor (Stormwind City)" },
    } },
  { map = "Darkshore", x = 30.6, y = 40.8, t = "boat", name = "Auberdine - Alah'Thalas Dock", faction = "A",
    dest = "Windrunner Pier (Alah'Thalas)", destmap = "Alah'Thalas",
    note = "Separate dock northwest of the main pier" },
  { map = "Teldrassil", x = 55.9, y = 93.5, t = "boat", name = "Rut'theran Village Pier",
    dest = "Auberdine (Darkshore)", destmap = "Darkshore",
    time = "Crossing: ~1-2 min", freq = "Departs: ~every 4-5 min" },
  { map = "Dustwallow Marsh", x = 71.6, y = 56.1, t = "boat", name = "Theramore Isle Dock",
    dest = "Menethil Harbor (Wetlands)", destmap = "Wetlands",
    time = "Crossing: ~3-5 min", freq = "Departs: ~every 7-10 min" },
  { map = "The Barrens", x = 63.7, y = 38.5, t = "boat", name = "Ratchet Dock",
    dest = "Booty Bay (Stranglethorn Vale)", destmap = "Stranglethorn Vale",
    time = "Crossing: ~2 min", freq = "Departs: ~every 6 min" },
  { map = "Stranglethorn Vale", x = 26.2, y = 73.4, t = "boat", name = "Booty Bay Dock",
    dest = "Ratchet (The Barrens)", destmap = "The Barrens",
    time = "Crossing: ~2 min", freq = "Departs: ~every 6 min" },
  { map = "Feralas", x = 30.9, y = 39.8, t = "boat", name = "Feathermoon Stronghold Dock",
    dest = "The Forgotten Coast (mainland Feralas)",
    time = "Crossing: ~1 min", freq = "Round trip 4:20, docks 30s" },
  { map = "Feralas", x = 43.3, y = 42.9, t = "boat", name = "The Forgotten Coast Dock",
    dest = "Feathermoon Stronghold (Sardor Isle)",
    time = "Crossing: ~2:20", freq = "Round trip 4:20, docks 30s" },

  -- ========================================================= zeppelins ==
  { map = "Durotar", x = 50.8, y = 13.2, t = "zeppelin", name = "Orgrimmar Zeppelin Tower", faction = "H",
    routes = {
      { dest = "Undercity (Tirisfal Glades) - south platform", time = "Crossing: ~1:40, cycle ~4 min" },
      { dest = "Grom'gol Base Camp (Stranglethorn Vale) - north platform", time = "Crossing: ~1:15, cycle ~4-5 min" },
    } },
  { map = "Tirisfal Glades", x = 61.0, y = 59.0, t = "zeppelin", name = "Undercity Zeppelin Tower", faction = "H",
    routes = {
      { dest = "Orgrimmar (Durotar) - west platform", time = "Crossing: ~1:40, cycle ~4 min" },
      { dest = "Grom'gol Base Camp (Stranglethorn Vale) - east platform", time = "Crossing: ~1:40, cycle ~5:15" },
    } },
  { map = "Stranglethorn Vale", x = 31.5, y = 29.6, t = "zeppelin", name = "Grom'gol Zeppelin Tower", faction = "H",
    routes = {
      { dest = "Orgrimmar (Durotar) - seaward side", time = "Crossing: ~1:30, cycle ~4-5 min" },
      { dest = "Undercity (Tirisfal Glades) - landward side", time = "Crossing: ~1:42, cycle ~5:15" },
    } },

  -- ============================================================== tram ==
  { map = "Stormwind City", x = 64.5, y = 7.5, t = "tram", name = "Deeprun Tram - Stormwind Station", faction = "A",
    dest = "Tinker Town (Ironforge)", destmap = "Ironforge",
    time = "Crossing: ~1 min", freq = "Two trams alternate; short waits" },
  { map = "Ironforge", x = 78.0, y = 51.4, t = "tram", name = "Deeprun Tram - Ironforge Station", faction = "A",
    dest = "Dwarven District (Stormwind City)", destmap = "Stormwind City",
    time = "Crossing: ~1 min", freq = "Two trams alternate; short waits" },

  -- ==================================================== flight masters ==
  -- Generated from the pfQuest-octo server database (meta "flight" x unit
  -- spawn coords) - includes Turtle/Octo custom flight points.
  { map = "Alah'Thalas", x = 43.4, y = 60.4, t = "flight", name = "Voryn Skystrider", faction = "A" },
  { map = "Alterac Mountains", x = 58.6, y = 80.2, t = "flight", name = "Zarise", faction = "H" },
  { map = "Arathi Highlands", x = 45.7, y = 46.1, t = "flight", name = "Cedrik Prose", faction = "A" },
  { map = "Arathi Highlands", x = 73, y = 32.7, t = "flight", name = "Urda", faction = "H" },
  { map = "Ashenvale", x = 12.2, y = 33.8, t = "flight", name = "Andruk", faction = "H" },
  { map = "Ashenvale", x = 34.4, y = 48, t = "flight", name = "Daelyshia", faction = "A" },
  { map = "Ashenvale", x = 73.2, y = 61.6, t = "flight", name = "Vhulgra", faction = "H" },
  { map = "Azshara", x = 11.9, y = 77.6, t = "flight", name = "Jarrodenus", faction = "A" },
  { map = "Azshara", x = 22, y = 49.6, t = "flight", name = "Kroum", faction = "H" },
  { map = "Badlands", x = 4, y = 44.8, t = "flight", name = "Gorrik", faction = "H" },
  { map = "Balor", x = 71, y = 46.2, t = "flight", name = "Hefeni", faction = "H" },
  { map = "Balor", x = 69.6, y = 78.4, t = "flight", name = "Nundir Feathersoar", faction = "A" },
  { map = "Blasted Lands", x = 65.5, y = 24.3, t = "flight", name = "Alexandra Constantine", faction = "A" },
  { map = "Burning Steppes", x = 84.3, y = 68.3, t = "flight", name = "Borgus Stoutarm", faction = "A" },
  { map = "Burning Steppes", x = 65.7, y = 24.2, t = "flight", name = "Vahgruk", faction = "H" },
  { map = "Darkshore", x = 50.1, y = 74.9, t = "flight", name = "Brakkar", faction = "H" },
  { map = "Darkshore", x = 36.3, y = 45.6, t = "flight", name = "Caylais Moonfeather", faction = "A" },
  { map = "Desolace", x = 64.7, y = 10.5, t = "flight", name = "Baritanas Skyriver", faction = "A" },
  { map = "Desolace", x = 21.6, y = 74.1, t = "flight", name = "Thalon", faction = "H" },
  { map = "Dun Morogh", x = 68.6, y = 18.7, t = "flight", name = "Falok Thurden", faction = "A",
    note = "Ironforge Airfield - unlocked by discovering Ironforge" },
  { map = "Dun Morogh", x = 26.9, y = 35.6, t = "flight", name = "Nelly Cogwheel", faction = "A" },
  { map = "Dun Morogh", x = 96.1, y = 47.1, t = "flight", name = "Thorgrum Borrelson", faction = "A" },
  { map = "Duskwood", x = 77.5, y = 44.3, t = "flight", name = "Felicia Maline", faction = "A" },
  { map = "Dustwallow Marsh", x = 67.5, y = 51.3, t = "flight", name = "Baldruc", faction = "A" },
  { map = "Dustwallow Marsh", x = 42.8, y = 72.5, t = "flight", name = "Razzit" },
  { map = "Dustwallow Marsh", x = 35.6, y = 31.9, t = "flight", name = "Shardi", faction = "H" },
  { map = "Eastern Plaguelands", x = 80.2, y = 57, t = "flight", name = "Georgia", faction = "H" },
  { map = "Eastern Plaguelands", x = 81.6, y = 59.3, t = "flight", name = "Khaelyn Steelwing", faction = "A" },
  { map = "Felwood", x = 34.4, y = 54, t = "flight", name = "Brakkar", faction = "H" },
  { map = "Felwood", x = 62.5, y = 24.2, t = "flight", name = "Mishellena", faction = "A" },
  { map = "Feralas", x = 30.2, y = 43.2, t = "flight", name = "Fyldren Moonfeather", faction = "A" },
  { map = "Feralas", x = 75.4, y = 44.4, t = "flight", name = "Shyn", faction = "H" },
  { map = "Feralas", x = 89.5, y = 45.9, t = "flight", name = "Thyssiana", faction = "A" },
  { map = "Gillijim's Isle", x = 70.1, y = 76.2, t = "flight", name = "Nal'rak", faction = "H",
    note = "Mosh'ogg Refuge - unlocked by discovering Booty Bay" },
  { map = "Gilneas", x = 57.1, y = 38.4, t = "flight", name = "Andana", faction = "H" },
  { map = "Gilneas", x = 62, y = 74, t = "flight", name = "Maria Galwest", faction = "A" },
  { map = "Gnomeregan", x = 96.8, y = 63.6, t = "flight", name = "Nelly Cogwheel", faction = "A" },
  { map = "Grim Reaches", x = 51.7, y = 56.8, t = "flight", name = "Krangosh Thunderwind", faction = "A" },
  { map = "Grim Reaches", x = 60, y = 30.9, t = "flight", name = "Razikgar", faction = "H" },
  { map = "Grim Reaches", x = 15.9, y = 70.3, t = "flight", name = "Thorgrum Borrelson", faction = "A" },
  { map = "Hillsbrad Foothills", x = 49.3, y = 52.3, t = "flight", name = "Darla Harris", faction = "A" },
  { map = "Hillsbrad Foothills", x = 95.9, y = 5.5, t = "flight", name = "Guthrum Thunderfist", faction = "A" },
  { map = "Hillsbrad Foothills", x = 60.1, y = 18.6, t = "flight", name = "Zarise", faction = "H" },
  { map = "Hyjal", x = 81.4, y = 29.2, t = "flight", name = "Levenda Skytalon" },
  { map = "Ironforge", x = 55.5, y = 47.7, t = "flight", name = "Gryth Thurden", faction = "A" },
  { map = "Lapidis Isle", x = 60.2, y = 43, t = "flight", name = "Vanessa Porter", faction = "A",
    note = "Caelan's Rest - unlocked by discovering Booty Bay" },
  { map = "Loch Modan", x = 33.9, y = 51, t = "flight", name = "Thorgrum Borrelson", faction = "A" },
  { map = "Moonglade", x = 32.1, y = 66.6, t = "flight", name = "Faustron", faction = "H" },
  { map = "Moonglade", x = 48.1, y = 67.3, t = "flight", name = "Sindrayl", faction = "A" },
  { map = "Mulgore", x = 39.4, y = 27, t = "flight", name = "Tal", faction = "H" },
  { map = "Northwind", x = 45.5, y = 57.8, t = "flight", name = "Leonhart Hamel", faction = "A" },
  { map = "Orgrimmar", x = 45.1, y = 63.9, t = "flight", name = "Doras", faction = "H" },
  { map = "Redridge Mountains", x = 30.6, y = 59.4, t = "flight", name = "Ariena Stormfeather", faction = "A" },
  { map = "Scarlet Enclave", x = 39.3, y = 36, t = "flight", name = "Georgia", faction = "H" },
  { map = "Scarlet Enclave", x = 41, y = 38.8, t = "flight", name = "Khaelyn Steelwing", faction = "A" },
  { map = "Searing Gorge", x = 83.2, y = 35.8, t = "flight", name = "Gorrik", faction = "H" },
  { map = "Searing Gorge", x = 34.8, y = 30.9, t = "flight", name = "Grisha", faction = "H" },
  { map = "Searing Gorge", x = 37.9, y = 30.9, t = "flight", name = "Lanie Reed", faction = "A" },
  { map = "Silithus", x = 50.6, y = 34.4, t = "flight", name = "Cloud Skydancer", faction = "A" },
  { map = "Silithus", x = 48.7, y = 36.7, t = "flight", name = "Runk Windtamer", faction = "H" },
  { map = "Silverpine Forest", x = 45.6, y = 42.6, t = "flight", name = "Karos Razok", faction = "H" },
  { map = "Stonetalon Mountains", x = 43.6, y = 82.4, t = "flight", name = "Baritanas Skyriver", faction = "A" },
  { map = "Stonetalon Mountains", x = 79.4, y = 63.9, t = "flight", name = "Orrik Thunderbeard", faction = "A" },
  { map = "Stonetalon Mountains", x = 41.3, y = 18.9, t = "flight", name = "Teloren", faction = "A" },
  { map = "Stonetalon Mountains", x = 48.3, y = 61.7, t = "flight", name = "Tharm", faction = "H" },
  { map = "Stormwind City", x = 71, y = 72.5, t = "flight", name = "Dungar Longdrink", faction = "A" },
  { map = "Stranglethorn Vale", x = 26.9, y = 77.1, t = "flight", name = "Gringer", faction = "H" },
  { map = "Stranglethorn Vale", x = 27.5, y = 77.8, t = "flight", name = "Gyll", faction = "A" },
  { map = "Stranglethorn Vale", x = 32.5, y = 29.4, t = "flight", name = "Thysta", faction = "H" },
  { map = "Swamp of Sorrows", x = 46.1, y = 54.8, t = "flight", name = "Breyk", faction = "H" },
  { map = "Tanaris", x = 51, y = 29.3, t = "flight", name = "Bera Stonehammer", faction = "A" },
  { map = "Tanaris", x = 51.6, y = 25.4, t = "flight", name = "Bulkrek Ragefist", faction = "H" },
  { map = "Tanaris", x = 24.6, y = 74.2, t = "flight", name = "Treggi" },
  { map = "Tel'Abim", x = 39.4, y = 78, t = "flight", name = "Tezzin Skyfuse" },
  { map = "Teldrassil", x = 58.4, y = 94, t = "flight", name = "Vesprystus", faction = "A" },
  { map = "Thalassian Highlands", x = 58.4, y = 30.8, t = "flight", name = "Voryn Skystrider", faction = "A" },
  { map = "The Barrens", x = 63.1, y = 37.2, t = "flight", name = "Bragok" },
  { map = "The Barrens", x = 51.5, y = 30.3, t = "flight", name = "Devrak", faction = "H" },
  { map = "The Barrens", x = 44.4, y = 59.2, t = "flight", name = "Omusa Thunderhorn", faction = "H" },
  { map = "The Barrens", x = 34.1, y = 10.9, t = "flight", name = "Orrik Thunderbeard", faction = "A" },
  { map = "The Barrens", x = 53.9, y = 70.5, t = "flight", name = "Shardi", faction = "H" },
  { map = "The Hinterlands", x = 81.7, y = 81.8, t = "flight", name = "Gorkas", faction = "H" },
  { map = "The Hinterlands", x = 11.1, y = 46.2, t = "flight", name = "Guthrum Thunderfist", faction = "A" },
  { map = "Thousand Needles", x = 45.1, y = 49.1, t = "flight", name = "Nyse", faction = "H" },
  { map = "Thousand Needles", x = 7.8, y = 17.9, t = "flight", name = "Thyssiana", faction = "A" },
  { map = "Thunder Bluff", x = 47, y = 49.8, t = "flight", name = "Tal", faction = "H" },
  { map = "Tirisfal Glades", x = 4.1, y = 60.7, t = "flight", name = "Mary Willowfield", faction = "H" },
  { map = "Un'Goro Crater", x = 45.2, y = 5.8, t = "flight", name = "Gryfe" },
  { map = "Undercity", x = 63.3, y = 48.6, t = "flight", name = "Michael Garrett", faction = "H" },
  { map = "Western Plaguelands", x = 42.9, y = 85.1, t = "flight", name = "Bibilfaz Featherwhistle", faction = "A" },
  { map = "Westfall", x = 56.6, y = 52.6, t = "flight", name = "Thor", faction = "A" },
  { map = "Wetlands", x = 22.7, y = 65.4, t = "flight", name = "Greta Stonehammer", faction = "A",
    note = "Dun Agrath - unlocked by discovering Menethil Harbor" },
  { map = "Wetlands", x = 9.5, y = 59.7, t = "flight", name = "Shellei Brondir", faction = "A" },
  { map = "Winterspring", x = 62.3, y = 36.6, t = "flight", name = "Maethrya", faction = "A" },
  { map = "Winterspring", x = 60.5, y = 36.3, t = "flight", name = "Yugrek", faction = "H" },
  { map = "Moonwhisper Coast", x = 58.3, y = 24.7, t = "flight", name = "Merellanea", faction = "A",
    note = "Narvalis Point" },
  { map = "Moonwhisper Coast", x = 65.4, y = 38.5, t = "flight", name = "Sol Greycloud", faction = "H",
    note = "Moonhoof Village" },
  { map = "Moonglade", x = 44.1, y = 45.2, t = "flight", name = "Silva Fil'naveth", faction = "A",
    note = "Druids only (Nighthaven)" },
  { map = "Moonglade", x = 44.3, y = 45.9, t = "flight", name = "Bunthen Plainswind", faction = "H",
    note = "Druids only (Nighthaven)" },

  -- ================================== Turtle/Octo custom boats & ships ==
  { map = "Stormwind City", x = 21.7, y = 56.5, t = "boat", name = "Stormwind Harbor", faction = "A",
    dest = "Auberdine (Darkshore)", destmap = "Darkshore",
    note = "Southernmost pier of the harbor" },
  { map = "Durotar", x = 61.3, y = 26.4, t = "boat", name = "Sparkwater Port Dock", faction = "H",
    dest = "Revantusk Village (The Hinterlands)", destmap = "The Hinterlands",
    note = "Dockworker Shazklench" },
  { map = "Durotar", x = 57.6, y = 28.1, t = "zeppelin", name = "Sparkwater Flying Machine", faction = "H",
    dest = "Gazzik's Workshop (Blackstone Island)", destmap = "Blackstone Island" },
  { map = "The Hinterlands", x = 81.6, y = 82.4, t = "boat", name = "Revantusk Village Dock", faction = "H",
    dest = "Sparkwater Port (Durotar)", destmap = "Durotar",
    note = "Dockmaster Tin'go" },
  { map = "Alah'Thalas", x = 53.1, y = 4.7, t = "boat", name = "Windrunner Pier", faction = "A",
    dest = "Auberdine (Darkshore)", destmap = "Darkshore",
    note = "North of the city; Captain Velari Shadelain" },
  { map = "Thalassian Highlands", x = 63.1, y = 4.4, t = "boat", name = "Windrunner Pier", faction = "A",
    dest = "Auberdine (Darkshore)", destmap = "Darkshore" },
  { map = "Darkshore", x = 56.7, y = 11.6, t = "boat", name = "Northeast Passage Ferry",
    dest = "Icepoint Rock", destmap = "Icepoint Rock",
    note = "Talk to Inunquaq the tuskarr; instant crossing, no boat" },
  { map = "Icepoint Rock", x = 61.5, y = 69.9, t = "boat", name = "Icepoint Rock Ferry",
    dest = "Darkshore", destmap = "Darkshore",
    note = "Talk to Inunquaq the tuskarr; instant crossing, no boat" },
  { map = "Moonwhisper Coast", x = 69.2, y = 38.3, t = "boat", name = "Moonhoof Village Dock", faction = "H",
    dest = "Shadowprey Village (Desolace)", destmap = "Desolace" },
  { map = "Desolace", x = 21.1, y = 74.3, t = "boat", name = "Shadowprey Village Dock", faction = "H",
    dest = "Moonhoof Village (Moonwhisper Coast)", destmap = "Moonwhisper Coast" },
  { map = "Tirisfal Glades", x = 3.5, y = 60.6, t = "boat", name = "Steepcliff Port", faction = "H",
    note = "Dockmaster Ormen. No boat route documented; use the flight path." },
  { map = "Blackstone Island", x = 63.7, y = 82.3, t = "zeppelin", name = "Gazzik's Flying Machine", faction = "H",
    dest = "Sparkwater Port (Durotar)", destmap = "Durotar",
    note = "Gazzik's Workshop" },

  -- ===================================== Turtle/Octo custom zeppelins ==
  { map = "Mulgore", x = 32.5, y = 22.0, t = "zeppelin", name = "Thunder Bluff Zeppelin Tower", faction = "H",
    dest = "Orgrimmar - west tower (Durotar)", destmap = "Durotar" },
  { map = "Durotar", x = 41.4, y = 18.4, t = "zeppelin", name = "Orgrimmar Zeppelin Tower (west)", faction = "H",
    routes = {
      { dest = "Thunder Bluff (Mulgore)" },
      { dest = "Kargath (Badlands)" },
    },
    note = "Tizak Boltratch and Razen Mudvalve" },
  { map = "Badlands", x = 6.0, y = 46.9, t = "zeppelin", name = "Kargath Zeppelin Tower", faction = "H",
    dest = "Orgrimmar (Durotar)", destmap = "Durotar",
    note = "Merk Boltratch" },

  -- ============================== Turtle/Octo portals & teleporters ==
  { map = "Alah'Thalas", x = 26.0, y = 67.5, t = "portal", name = "Golden Dawn Institute Portals", faction = "A",
    icon = "Interface\\Icons\\Spell_Arcane_PortalStormWind",
    routes = {
      { dest = "Stormwind City" },
      { dest = "Ironforge" },
      { dest = "Darnassus" },
    } },
  { map = "Alah'Thalas", x = 37.6, y = 69.5, t = "portal", name = "City Teleport Orb", faction = "A",
    note = "Teleports within Alah'Thalas" },
  { map = "Hyjal", x = 81.7, y = 35.2, t = "portal", name = "Runestone of Nordrassil",
    note = "Hyjal runestone teleport network; Nordanaar rune unlocked by quest" },
  { map = "Hyjal", x = 64.7, y = 76.8, t = "portal", name = "Runestone of Cenarius",
    note = "Hyjal runestone teleport network" },
  { map = "Moonwhisper Coast", x = 70.9, y = 64.6, t = "portal", name = "Maras'ethil Runestone",
    note = "Runestone teleport network" },
  { map = "Moonwhisper Coast", x = 45.6, y = 33.9, t = "portal", name = "N'las' Runestone",
    note = "Runestone teleport network" },

  -- ========================================== rentable mounts (Turtle) ==
  -- Coords from the pfQuest-octo db. Starting-zone rentals since 1.18:
  -- ~1s for 5 min at +40% speed; mount vanishes on dismount.
  { map = "Elwynn Forest", x = 42.3, y = 63.8, t = "rental", name = "Goldshire Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)", note = "Two horses by the inn" },
  { map = "Elwynn Forest", x = 60.0, y = 29.5, t = "rental", name = "Horse Rental (Stone Cairn Lake)", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Westfall", x = 58.1, y = 53.2, t = "rental", name = "Sentinel Hill Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Redridge Mountains", x = 30.8, y = 46.3, t = "rental", name = "Lakeshire Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Duskwood", x = 92.6, y = 13.6, t = "rental", name = "Horse Rental (northeast Duskwood)", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Stormwind City", x = 29.8, y = 13.4, t = "rental", name = "Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Stormwind City", x = 30.4, y = 27.7, t = "rental", name = "Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Blasted Lands", x = 66.6, y = 21.9, t = "rental", name = "Nethergarde Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Western Plaguelands", x = 81.0, y = 61.6, t = "rental", name = "Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Eastern Plaguelands", x = 22.8, y = 85.2, t = "rental", name = "Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Wetlands", x = 8.0, y = 54.3, t = "rental", name = "Menethil Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Wetlands", x = 10.6, y = 59.8, t = "rental", name = "Menethil Ram Rental", faction = "A",
    icon = "Interface\\Icons\\Ability_Mount_MountainRam",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Northwind", x = 32.5, y = 84.6, t = "rental", name = "Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Northwind", x = 40.1, y = 68.2, t = "rental", name = "Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Northwind", x = 32.8, y = 92.3, t = "rental", name = "Horse Rental", faction = "A",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  -- Horde wolves
  { map = "Durotar", x = 51.5, y = 42.4, t = "rental", name = "Razor Hill Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)", note = "The Razor Hill wolves" },
  { map = "Durotar", x = 44.7, y = 12.8, t = "rental", name = "Wolf Rental (outside Orgrimmar)", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Orgrimmar", x = 46.0, y = 97.9, t = "rental", name = "Wolf Rental (Main Gate)", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "The Barrens", x = 51.7, y = 29.6, t = "rental", name = "Crossroads Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "The Barrens", x = 43.8, y = 91.9, t = "rental", name = "Wolf Rental (Great Lift)", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "The Barrens", x = 61.8, y = 24.0, t = "rental", name = "Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "The Barrens", x = 64.9, y = 34.3, t = "rental", name = "Ratchet Rental (horse, ram)",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Stranglethorn Vale", x = 31.9, y = 29.5, t = "rental", name = "Grom'gol Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Swamp of Sorrows", x = 45.4, y = 52.6, t = "rental", name = "Stonard Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Swamp of Sorrows", x = 51.3, y = 47.1, t = "rental", name = "Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Badlands", x = 3.6, y = 47.8, t = "rental", name = "Kargath Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Searing Gorge", x = 82.8, y = 39.2, t = "rental", name = "Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Ashenvale", x = 70.9, y = 68.3, t = "rental", name = "Splintertree Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Stonetalon Mountains", x = 50.2, y = 62.9, t = "rental", name = "Sun Rock Wolf Rental", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  { map = "Thousand Needles", x = 31.5, y = 21.5, t = "rental", name = "Wolf Rental (Great Lift)", faction = "H",
    icon = "Interface\\Icons\\Ability_Mount_WhiteDireWolf",
    price = "Rent: ~1s for 5 min (+40% speed)" },
  -- neutral rental hubs
  { map = "Tanaris", x = 50.8, y = 26.4, t = "rental", name = "Gadgetzan Mount Rental",
    price = "Rent: ~1s for 5 min (+40% speed)", note = "Horses, rams and wolves" },
  { map = "Winterspring", x = 60.5, y = 37.9, t = "rental", name = "Everlook Ram Rental",
    icon = "Interface\\Icons\\Ability_Mount_MountainRam",
    price = "Rent: ~1s for 5 min (+40% speed)" },

  -- ========================================== dungeons (open on Octo) ==
  -- Entrances anchored to meeting stone spawns from the server database;
  -- RFK/RFD/BRM north use well-known entrance coords. lft = queueable in
  -- the in-game group finder (click the pin to open it).
  { map = "Orgrimmar", x = 51.4, y = 48.7, t = "dungeon", name = "Ragefire Chasm", faction = "H",
    info = "Level 13-19, 5 players", lft = 1 },
  { map = "Westfall", x = 41.6, y = 72.4, t = "dungeon", name = "The Deadmines",
    info = "Level 16-24, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "The Barrens", x = 47.0, y = 35.6, t = "dungeon", name = "Wailing Caverns",
    info = "Level 16-25, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Silverpine Forest", x = 46.2, y = 68.4, t = "dungeon", name = "Shadowfang Keep",
    info = "Level 20-28, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Stormwind City", x = 53.2, y = 70.3, t = "dungeon", name = "The Stockade", faction = "A",
    info = "Level 23-32, 5 players", lft = 1 },
  { map = "Ashenvale", x = 15.4, y = 15.6, t = "dungeon", name = "Blackfathom Deeps",
    info = "Level 22-31, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Darkshore", x = 32.5, y = 97.5, t = "dungeon", name = "Blackfathom Deeps",
    info = "Level 22-31, 5 players", note = "Entrance just across the Ashenvale border", lft = 1 },
  { map = "Dun Morogh", x = 24.3, y = 40.4, t = "dungeon", name = "Gnomeregan",
    info = "Level 28-37, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "The Barrens", x = 40.8, y = 94.5, t = "dungeon", name = "Razorfen Kraul",
    info = "Level 29-36, 5 players", note = "Meeting stone nearby", lft = 1 },
  { map = "Tirisfal Glades", x = 82.1, y = 39.2, t = "dungeon", name = "Scarlet Monastery",
    info = "Level 30-45, 5 players", note = "Four wings: Graveyard, Library, Armory, Cathedral", lft = 1 },
  { map = "The Barrens", x = 50.9, y = 93.7, t = "dungeon", name = "Razorfen Downs",
    info = "Level 35-44, 5 players", note = "Meeting stone nearby", lft = 1 },
  { map = "Badlands", x = 49.1, y = 13.7, t = "dungeon", name = "Uldaman",
    info = "Level 41-50, 5 players", note = "Back entrance in southern Loch Modan (47, 89)", lft = 1 },
  { map = "Loch Modan", x = 47.3, y = 88.6, t = "dungeon", name = "Uldaman (back entrance)",
    info = "Level 41-50, 5 players", lft = 1 },
  { map = "Tanaris", x = 38.5, y = 20.7, t = "dungeon", name = "Zul'Farrak",
    info = "Level 42-51, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Desolace", x = 31.5, y = 62.4, t = "dungeon", name = "Maraudon",
    info = "Level 43-54, 5 players; three wings", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Swamp of Sorrows", x = 69.1, y = 54.7, t = "dungeon", name = "The Temple of Atal'Hakkar",
    info = "Level 49-58, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Burning Steppes", x = 29.8, y = 28.7, t = "dungeon", name = "Blackrock Depths",
    info = "Level 50-60, 5 players", note = "Inside Blackrock Mountain; leads to Molten Core", lft = 1 },
  { map = "Burning Steppes", x = 32.8, y = 30.4, t = "dungeon", name = "Blackrock Spire",
    info = "Level 55-60; LBRS 5, UBRS 10 players", note = "Inside Blackrock Mountain", lft = 1 },
  { map = "Searing Gorge", x = 35.4, y = 84.4, t = "dungeon", name = "Blackrock Mountain (north entrance)",
    info = "BRD, Blackrock Spire and Molten Core inside", lft = 1 },
  { map = "Feralas", x = 58.0, y = 44.5, t = "dungeon", name = "Dire Maul",
    info = "Level 55-60, 5 players", note = "Three wings; meeting stone at the entrance", lft = 1 },
  { map = "Eastern Plaguelands", x = 30.9, y = 16.6, t = "dungeon", name = "Stratholme",
    info = "Level 58-60, 5 players", note = "Meeting stone at the main gate", lft = 1 },
  { map = "Western Plaguelands", x = 69.5, y = 74.5, t = "dungeon", name = "Scholomance",
    info = "Level 58-60, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  -- Turtle/Octo custom dungeons
  { map = "Dun Morogh", x = 69.2, y = 19.3, t = "dungeon", name = "Frostmane Hollow",
    info = "Level 13-20, 5 players", note = "Near Ironforge Airfield", lft = 1 },
  { map = "Thousand Needles", x = 68.6, y = 41.8, t = "dungeon", name = "Windhorn Caverns",
    info = "Level 25-33, 5 players", lft = 1 },
  { map = "Balor", x = 51.0, y = 66.4, t = "dungeon", name = "Stormwrought Ruins",
    info = "Two wings: Castle 32-40, Descent 35-44", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Ashenvale", x = 51.9, y = 76.5, t = "dungeon", name = "The Crescent Grove",
    info = "Level 33-39, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Gilneas", x = 28.1, y = 28.3, t = "dungeon", name = "Gilneas City",
    info = "Level 43-52, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Burning Steppes", x = 94.0, y = 55.3, t = "dungeon", name = "Hateforge Quarry",
    info = "Level 51-60, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Deadwind Pass", x = 39.6, y = 75.6, t = "dungeon", name = "Karazhan Crypt",
    info = "Level 60, 5 players", note = "Meeting stone at the graveyard entrance", lft = 1 },
  { map = "Stormwind City", x = 62.4, y = 60.9, t = "dungeon", name = "Stormwind Vault", faction = "A",
    info = "Level 60, 5 players", note = "Meeting stone at the entrance", lft = 1 },
  { map = "Tanaris", x = 65.1, y = 50.5, t = "dungeon", name = "Caverns of Time: Black Morass",
    info = "Level 60, 5 players", note = "Meeting stone at the cavern entrance", lft = 1 },
  { map = "Wetlands", x = 64.0, y = 63.6, t = "dungeon", name = "Dragonmaw Retreat",
    info = "Level 26-35, 5 players", note = "Near Grim Batol; meeting stone at the entrance", lft = 1 },

  -- ================================================ raids (open only) ==
  -- Phased raids (ZG, BWL, Emerald Sanctum, AQ, Timbermaw Hold, Naxx,
  -- Tower of Karazhan) get added when the Octo roadmap opens them.
  { map = "Burning Steppes", x = 30.7, y = 30.5, t = "raid", name = "Molten Core",
    info = "Level 60, 40-player raid", note = "Enter through Blackrock Depths; attunement quest skips the walk" },
  { map = "Dustwallow Marsh", x = 52.0, y = 76.5, t = "raid", name = "Onyxia's Lair",
    info = "Level 60, 40-player raid", note = "Attunement required" },
  { map = "Deadwind Pass", x = 40.9, y = 73.5, t = "raid", name = "Lower Karazhan Halls",
    info = "Level 60, 10-player raid", note = "Tower gate; attunement required" },

  -- ===================================================== world bosses ==
  -- Spawn points from the server database. Spawns are not on a fixed
  -- schedule; the pin marks where the boss appears.
  { map = "Azshara", x = 56.8, y = 78.7, t = "worldboss", name = "Azuregos",
    info = "Level 60 world boss (raid)" },
  { map = "Blasted Lands", x = 35.6, y = 74.3, t = "worldboss", name = "Lord Kazzak",
    info = "Level 60 world boss (raid)" },
  { map = "The Hinterlands", x = 62.3, y = 23.3, t = "worldboss", name = "Ysondre",
    info = "Level 60 world boss (raid)", note = "Emerald dragon; the four rotate among the Dream portals" },
  { map = "Feralas", x = 51.2, y = 10.9, t = "worldboss", name = "Lethon",
    info = "Level 60 world boss (raid)", note = "Emerald dragon; Dream Bough portal" },
  { map = "Duskwood", x = 45.4, y = 39.6, t = "worldboss", name = "Emeriss",
    info = "Level 60 world boss (raid)", note = "Emerald dragon; Twilight Grove portal" },
  { map = "Ashenvale", x = 94.2, y = 35.7, t = "worldboss", name = "Taerar",
    info = "Level 60 world boss (raid)", note = "Emerald dragon; Bough Shadow portal" },
  { map = "Eastern Plaguelands", x = 8.1, y = 38.2, t = "worldboss", name = "Nerubian Overseer",
    info = "Level 60 world boss (raid)" },
  { map = "Deadwind Pass", x = 47.1, y = 75.2, t = "worldboss", name = "Dark Reaver of Karazhan",
    info = "Level 60 world boss (raid)" },
  { map = "Desolace", x = 82.0, y = 80.6, t = "worldboss", name = "Concavius",
    info = "Level 60 world boss (raid)", note = "Also spawns in Mulgore (29, 49)" },
}
